apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: latency-collector
    app.kubernetes.io/part-of: latency-collector
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: latency-collector-helper
  namespace: system
data:
  get-kubeconfig.sh: |
    #!/bin/sh
    CP="$1"        # controlplane name or WEC context
    MODE="$2"      # "in" for in-cluster, "ex" for external
    FIELD="$([ "$MODE" = "in" ] && echo inClusterKey || echo key)"
    SN=$(kubectl get controlplane "$CP" -o=jsonpath='{.status.secretRef.name}')
    SNS=$(kubectl get controlplane "$CP" -o=jsonpath='{.status.secretRef.namespace}')
    DK=$(kubectl get controlplane "$CP" -o=jsonpath="{.status.secretRef.${FIELD}}")
    kubectl get secret "$SN" -n "$SNS" -o=jsonpath="{.data.${DK}}" | base64 -d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: latency-collector
    app.kubernetes.io/part-of: latency-collector
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: controller-manager
      volumes:
        - name: helper
          configMap:
            name: latency-collector-helper
            defaultMode: 0755
        - name: shared
          emptyDir: {}
      initContainers:
        - name: init-wds
          image: quay.io/kubestellar/kubectl:1.27.8
          command:
            - /bin/sh
            - -c
            - /mnt/helper/get-kubeconfig.sh wds in > /mnt/shared/wds.kubeconfig
          volumeMounts:
            - name: helper
              mountPath: /mnt/helper
            - name: shared
              mountPath: /mnt/shared

        - name: init-its
          image: quay.io/kubestellar/kubectl:1.27.8
          command:
            - /bin/sh
            - -c
            - /mnt/helper/get-kubeconfig.sh its in > /mnt/shared/its.kubeconfig
          volumeMounts:
            - name: helper
              mountPath: /mnt/helper
            - name: shared
              mountPath: /mnt/shared

        - name: init-wec-cluster1
          image: quay.io/kubestellar/kubectl:1.27.8
          command:
            - /bin/sh
            - -c
            - /mnt/helper/get-kubeconfig.sh cluster1 ex > /mnt/shared/wec-cluster1.kubeconfig
          volumeMounts:
            - name: helper
              mountPath: /mnt/helper
            - name: shared
              mountPath: /mnt/shared

        - name: init-wec-cluster2
          image: quay.io/kubestellar/kubectl:1.27.8
          command:
            - /bin/sh
            - -c
            - /mnt/helper/get-kubeconfig.sh cluster2 ex > /mnt/shared/wec-cluster2.kubeconfig
          volumeMounts:
            - name: helper
              mountPath: /mnt/helper
            - name: shared
              mountPath: /mnt/shared

      containers:
        - name: manager
          image: asmitk1927/ks-latency:v0.7.2
          imagePullPolicy: Always
          args:
            - --leader-elect
            - --metrics-bind-address=:2222
            - --kubeconfig=/mnt/shared/manager.kubeconfig
            - --wds-kubeconfig=/mnt/shared/wds.kubeconfig
            - --its-kubeconfig=/mnt/shared/its.kubeconfig
            - --wec-kubeconfigs=/mnt/shared/wec-cluster1.kubeconfig,/mnt/shared/wec-cluster2.kubeconfig
          volumeMounts:
            - name: shared
              mountPath: /mnt/shared
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10