# permissions for end users to edit latencycollectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: latencycollector-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: latency-collector
    app.kubernetes.io/part-of: latency-collector
    app.kubernetes.io/managed-by: kustomize
  name: latencycollector-editor-role
rules:
- apiGroups:
  - control.kubestellar.io
  resources:
  - latencycollectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - control.kubestellar.io
  resources:
  - latencycollectors/status
  verbs:
  - get
