apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: latency-collector-manager-rolebinding
  labels:
    app.kubernetes.io/part-of: latency-collector
    app.kubernetes.io/created-by: latency-collector
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: latency-collector-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: latency-collector-manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
